### ISSUE TITLE
Mouse or Pad?

### ISSUE THREAD

**Issue by SimonFili** [antonialoytorrens/TF101-linux-images#1]
Hi there!  Thanks for this work!  Fun to see Linux on my old TF101 I was about to throw in the garbage bin!

Did you find a way to make a mouse or the TF101 pad work?

I have tried to use a USB stick mouse but not detected.

lsusb show a new device (Microsoft USB stick), but not detected as a mouse.

UPDATE: I installed usbutils "sudo apk add usbutils" and a wired mouse works!
UPDATE2: Plugged in the USB wireless stick, did not work, but after a reboot, works!  So full wireless mouse/keyboard! 

;-)

**Comment by antonialoytorrens** [comment]
usbutils package was not installed in my image? Oops, my bad, glad you solved the issue!
