### ISSUE TITLE
Web browser

### ISSUE THREAD

**Issue by SimonFili** [antonialoytorrens/TF101-linux-images#2]
Tested some web browser installs.

The goal is to find a browser that can load the node-red UI

1) The integrated web browser works ok, but cannot load my target web site for this TF101
2) midori: I can almost load the UI of node-red, but some elements like graphs don't draw.
 - After a while, the connection is lost
3) Firefox does not load
4) epiphany does not load
5) konquerer does not load

So, basic browsing, the internal Netsurf browser works.
Midori can be better at some browsing, but not enough for Node-Red works

**Comment by antonialoytorrens** [comment]
Web browsing is what this PostmarketOS image lacks for. It is using a 3.x.x kernel, so newer browsers cannot support it.

The only method to get decent web browsing is using an EOL'ed image.
Please read the [README-rootbind.old](https://github.com/antonialoytorrens/TF101-linux-images/blob/master/README.rootbind-method.old) file if you urgently need "modern" web browsing.

I recommend you the [Jessie All Extras](https://sourceforge.net/projects/tf101-linux-images/files/debian-8.11-jessie-all/debian-8.11-jessie-all.tar.gz) image or the [Lubuntu 12.04](https://sourceforge.net/projects/tf101-linux-images/files/%5BLinux%5D%20%5BIMG%5D%20%5BDev%5D%20%5BWIP%5D%20Ubuntu%20images%20for%20Rootbind%20%5BTF101-TF101G%5D/tf101-12.04.4-Lubuntu-armhf-Tegra.tar.gz) one.

Please if you choose the Lubuntu image, make sure to run _apt-get update && apt-get dist-upgrade_ to update all the packages into 12.04.6 version.

**Comment by SimonFili** [comment]
Thanks for the info/help.

I think I'm missing something in my understanding.
1) I copied xfce-postmarketOS-TF101-v3.0.img to a flashcard that I inserted in the TF101
2) I used ADB to copy PostmarketOS-kernel-3.1.10-15-r2.zip to /sdcard
3) Inside TWRP (TF101) I used Install and selected the ZIP (Step2) to flash

Question 1: how was the IMG on the flashcard used?

Question 2: If I go with lUbuntu 12, it's a TGZ file, does it replace the zip in step2 above?
 - Do I need another IMG in the flashcard?

Thanks!

**Comment by antonialoytorrens** [comment]
1- Maybe I am misunderstanding something, but... have you actually _copied_ the img file to the SD Card? You have to _burn_ it with an img writer program. Which OS are you using?

2- No, it doesn't.
But I missed something in my explanation earlier:
If you use the Jessie or Lubuntu image, you have to replace the zip with [this](https://sourceforge.net/projects/tf101-linux-images/files/%5BLinux%5D%20%5BIMG%5D%20%5BDev%5D%20%5BWIP%5D%20Ubuntu%20images%20for%20Rootbind%20%5BTF101-TF101G%5D/Ubuntu-3.1.10-15-rootbind-oc1.5.zip) one.

• Do I need another IMG in the flashcard?
The PostmarketOS installation and the _Rootbind_ installation is very different from each other.
In the PostmarketOS installation, the image goes in SD Card.
In the _Rootbind_ installation, the image goes in Internal Memory.

If both README are still confusing for you, I'll post later a video showing both methods.

**Comment by SimonFili** [comment]
1) For the flashcard, yes I burned it per instructions
 - Using Windows 10.  I tried to use Ubuntu in a VM, but could not get the USB attached properly!
2) Ok so I don't need another IMG on the flashcard, only the TGZ copied to /sdcard... right?
 - I assume here I could "wipe" everything using TWRP to make space and clean-up?

I don't want to impose more on your time, I will try the TGZ copied with ADB to /sdcard and report back later.

Thanks!

**Comment by SimonFili** [comment]
@antonialoytorrens - Ok I think I'm missing something again!  Sorry!

I copied the Ubuntu-3.1.10-15-rootbind-oc1.5.zip with ADB to /sdcard.

Installed it with TWRP.  Rebooted but got to boot shell, so I'm missing the IMG on the SD Card, but unsure how to get this step done from a TGZ with disk imager?

Thanks!

**Comment by antonialoytorrens** [comment]
Oh, my bad! My head is out of place :P
So finally you chose TGZ file, you are almost done!
- You copied Ubuntu-3.1.10-15-rootbind-oc1.5.zip with ADB to /sdcard.
- You copied TGZ file into SD Card.

The last step is not quite correct, I'm sorry for misunderstanding you.
You have to copy TGZ file into /sdcard.
So, do these steps:

```
$ adb push /path/to/TGZ /sdcard
$ adb shell

# mkdir /data/linuxroot
# cd /data/linuxroot
# tar -xvzf /sdcard/TGZ


Wait 5 to 10 minutes to finish
```
Note: Yes, the folder has to be named linuxroot, otherwise it won't boot.

Flash Ubuntu-3.1.10-15-rootbind-oc1.5.zip. Done!

The SD Card is only needed when installing PostmarketOS.
When installing Lubuntu, no need of SD Card.


Note: remember to run `apt-get update && apt-get dist-upgrade` to have all packages up to date.
If node-red UI does not load on firefox, do the same but with the Debian image.

**Comment by SimonFili** [comment]
Thanks! I found the above instructions a few hours back and managed to install lubuntu. Unfortunately Node-Red UI is not loading properly in FF. But it's quite cool to have Ubuntu on this old tablet! 

FYI: Node-Red is hosted on a Raspberry Pi Zero, but UI pages load very fast on a fast PC. 

I tried to tweak FF but I get slow load page and disconnections.  The CPU is very high while loading the UI page, so I assume there's a lot of page rendering offloaded to the browser while the network traffic is low. 

The update manager tell me I could update to V 14.04.6 LTS, would the work? 

I will try Debian but doubt it will help. 

Is the Nvidia chipset supported on this lubuntu?

**Comment by antonialoytorrens** [comment]
Mind that the TF101 only has 1GB of RAM, it's the bare minimum nowadays to get browser working, so it can be very slow sometimes.

Yes, the Nvidia chipset is supported in this version (it's using Nvidia drivers), that's why I recommended it. You could upgrade to 14.04.6 but xserver and firefox won't work (you'll have to stick with 12.04.6 release). So in my opinion, I would not do that.

The only way to get modern Linux working here is installing PostmarketOS (with some features not working) or getting a working 5.x.x kernel in this tablet.

**Comment by SimonFili** [comment]
Thanks for everything @antonialoytorrens .

Even if I cannot load the Node-Red UI, I still have a good Linux portable machine I can do lots with... better than the garbage bin!

I think we have reached the end of the optimization, short of soldering a new memory chip, if at all possible.

**Comment by antonialoytorrens** [comment]
Of course, although web browsing requires lots of memory, it is still very usable for other stuff (like a lightweight computer), glad you liked it! Closing this issue.

**Comment by SimonFili** [comment]
![IMG_20201229_092936~2](https://user-images.githubusercontent.com/7669537/103291070-f9e0c700-49b8-11eb-81cf-966489d3c954.jpg)
Works for text panels of Node-Red.
