### ISSUE TITLE
how do i install debian 11 bullseye to internal storage instead of Micro SD Card?

### ISSUE THREAD

**Issue by CrazyPlaysHD** [antonialoytorrens/TF101-linux-images#5]
i saw this https://sourceforge.net/projects/tf101-linux-images/ **The Debian 11 Bullseye**

and how do i install it to my internal storage without a PC? i only have TWRP v2.8.1.1 recovery

**Comment by antonialoytorrens** [comment]
Installing the system in eMMC (aka internal storage) is still unsupported by the kernel.
I'll soon post the guide installing Debian 11 Bullseye, it's very similar to install mainline PostmarketOS.

Also, a PC (Linux suggested) is required for the installation.

Sorry for the inconvenience.
