### ISSUE TITLE
installation guide

### ISSUE THREAD

**Issue by c5c86a** [antonialoytorrens/TF101-linux-images#6]
Hi, noob here :)

1. Which Installation is the simplest? The old downstream release?
2. Is this installation guide more up to date than [this](https://wiki.postmarketos.org/wiki/ASUS_Eee_Pad_Transformer_(asus-tf101))? I assume so as the other one has the Installation section starting with the word "(deprecated)"
3. In the Introduction you say "I have used a computer with Linux in this guide" but then you say "APX Drivers (Windows only)", do I need both to install postmarketOS on TF101? Which linux distro did you use?

If there is a better place for such questions, let me know.

This is not an issue in your repo, it's amazing!

**Comment by antonialoytorrens** [comment]
> 1. Which Installation is the simplest? The old downstream release?

Yes, this is the _simplest_ installation is by using the old downstream release.

The mainline one is more responsive and uses a newer kernel with optimizations and new features, but it's trickier to get it working.

> 2. Is this installation guide more up to date than this? I assume so as the other one has the Installation section starting with the word "(deprecated)"

Yes, in fact, I modified this wiki page myself :)
I'll add this mainline method soon to match this guide.

> In the Introduction you say "I have used a computer with Linux in this guide" but then you say "APX Drivers (Windows only)", do I need both to install postmarketOS on TF101? Which linux distro did you use?

Sorry for not clarifying this enough. In the explanation, I meant to say that if you are using Windows, then you will need to install the APX Drivers.

In Linux, I think it comes along with adb. Open a terminal, type  `sudo apt install adb` and done. No need to install anything else.

I'm using Linux Mint 20.2 Uma, but I'm almost sure you can achieve it with Ubuntu 20.04, Debian 11 Bullseye or any other popular distribution.

Hope this helps you a little bit :)
