### ISSUE TITLE
Suspend support

### ISSUE THREAD

**Issue by LongnoseRob** [antonialoytorrens/TF101-linux-images#7]
After having the new mainline kernel working I was wondering, why I would see no mention of suspend in the menus.

Checking the config.gz I saw, that PM and suspend are in the kernel config.

after installing `pm-utils` suspend now works.

It might be a good idea to add this to the installation procedure.

**Comment by antonialoytorrens** [comment]
Thanks @LongnoseRob, very appreciated! For now, I've added it as an additional step in _3. Booting PostmarketOS_ section, but I'll add this utility in the next tested image, so no additional modification will be needed.

**Comment by LongnoseRob** [comment]
Great,

Thanks!
