### ISSUE TITLE
Ubuntu version to flash a new bootloader

### ISSUE THREAD

**Issue by CrazyPlaysHD** [antonialoytorrens/TF101-linux-images#9]
What ubuntu version do we need to install u-boot bootloader?

**Comment by antonialoytorrens** [comment]
Your question is a bit unclear:

* If you meant on which Linux am I (my host machine distribution):

Works on my Linux Mint 20.2 Uma (Ubuntu 20.04 focal), but it should work regardless of your Linux distribution.

* Which Linux OS has to be the tablet for a working U-Boot (remember that only works on micro SDCard)?

**PostmarketOS**: https://sourceforge.net/projects/tf101-linux-images/files/postmarketOS/mate-postmarketOS-TF101-v4.0.img.xz
**Debian**: https://sourceforge.net/projects/tf101-linux-images/files/debian-11-bullseye-grate/kernel-5.14.0-rc5/tf101-11.0-BullseyeXFCE-armhf-Tegra-kernel-5.14.0-rc5.img.xz

If you have more problems, feel free to ask.

**Comment by CrazyPlaysHD** [comment]
Oh I guess I have to dual boot windows 11 and Ubuntu 20.04

**Comment by CrazyPlaysHD** [comment]
I got Ubuntu 20.04 on my PC now but I still can't get tf101 detected now

"[ - ] Wheelie Did not detect a device in APX mode."

But I'm already in APX Mode

**Comment by antonialoytorrens** [comment]
I guess that you have downloaded this script, right? https://gitlab.com/antoni.aloytorrens/u-boot-tf101-tools<br/>
Also, have you installed adb? It might seem unrelated, but I have also got detection problems if I didn't install the package.

**Comment by antonialoytorrens** [comment]
> Oh I guess I have to dual boot windows 11 and Ubuntu 20.04

I guess that it would also work with Windows 11, but I think you have to run each of the lines that the script has manually (as Windows only run .bat files) and install the Universal Naked Drivers 0.73 for getting APX to work (the certificate is not valid anymore, so you have to install the "untrusted" certificate via some workarounds).

**Comment by CrazyPlaysHD** [comment]
> I guess that you have downloaded this script, right? https://gitlab.com/antoni.aloytorrens/u-boot-tf101-tools Also, have you installed adb? It might seem unrelated, but I have also got detection problems if I didn't install the package.

Yes I did

**Comment by CrazyPlaysHD** [comment]
> > Oh I guess I have to dual boot windows 11 and Ubuntu 20.04
> 
> I guess that it would also work with Windows 11, but I think you have to run each of the lines that the script has manually (as Windows only run .bat files) and install the Universal Naked Drivers 0.73 for getting APX to work (the certificate is not valid anymore, so you have to install the "untrusted" certificate via some workarounds).

installed UND 0.73 in windows 11 and i get this yellow exclamation mark from the device manager

[Screenshot From Device Manager](https://cdn.discordapp.com/attachments/847901416466022411/918846751375503390/Screenshot_2021-12-10_124734.png)

**Comment by antonialoytorrens** [comment]
> > > Oh I guess I have to dual boot windows 11 and Ubuntu 20.04
> > 
> > 
> > I guess that it would also work with Windows 11, but I think you have to run each of the lines that the script has manually (as Windows only run .bat files) and install the Universal Naked Drivers 0.73 for getting APX to work (the certificate is not valid anymore, so you have to install the "untrusted" certificate via some workarounds).
> 
> installed UND 0.73 in windows 11 and i get this yellow exclamation mark from the device manager
> 
> [Screenshot From Device Manager](https://cdn.discordapp.com/attachments/847901416466022411/918846751375503390/Screenshot_2021-12-10_124734.png)

Yes, that has happened to me.
Although I'm not using Windows very often (and my PC is stuck at Windows 10 due to requirements, I don't know if it will work on Windows 11), I remember waiting to get APX detected first before installing the driver for recognition.

Please try this approach, otherwise, I can't really tell why it's not working, which is really strange; as I have seen reports of users succeeding with the procedure.

**Comment by CrazyPlaysHD** [comment]
Someone told me that windows 10, 11 can't deal with tf101. Maybe I should try with windows 7

**Comment by antonialoytorrens** [comment]
Closing this: Replaced by #10 and #11.

**Comment by jbone899** [comment]
> Someone told me that windows 10, 11 can't deal with tf101. Maybe I should try with windows 7

You need to disable Driver Signing in the Advanced startup menu in order to install the Naked Drivers for the APX device. Go to Settings>Update>Recovery>Advanced startup. When it restarts, go to troubleshooting>advanced options>startup settings. F7, Driver Signature Enforcement needs to be disabled. When the device restarts, you will be able to install the driver for APX. Here is a link to the process...
https://www.tenforums.com/tutorials/156602-how-enable-disable-driver-signature-enforcement-windows-10-a.html

**Comment by antonialoytorrens** [comment]
> > Someone told me that windows 10, 11 can't deal with tf101. Maybe I should try with windows 7
> 
> You need to disable Driver Signing in the Advanced startup menu in order to install the Naked Drivers for the APX device. Go to Settings>Update>Recovery>Advanced startup. When it restarts, go to troubleshooting>advanced options>startup settings. F7, Driver Signature Enforcement needs to be disabled. When the device restarts, you will be able to install the driver for APX. Here is a link to the process... https://www.tenforums.com/tutorials/156602-how-enable-disable-driver-signature-enforcement-windows-10-a.html

Thanks for the assistance!
